// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW0Vk__nXs7ve1-o4M5LQeAEH-cmC8PBE',
    appId: '1:433205296996:web:8d0b2900465ecf44384471',
    messagingSenderId: '433205296996',
    projectId: 'bookme-e1f35',
    authDomain: 'bookme-e1f35.firebaseapp.com',
    storageBucket: 'bookme-e1f35.firebasestorage.app',
    measurementId: 'G-P6EGXKP7BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYNH35k33hFjYD09E9K1kGZoK7dUhOeC0',
    appId: '1:433205296996:android:42007e9d8dd787ec384471',
    messagingSenderId: '433205296996',
    projectId: 'bookme-e1f35',
    storageBucket: 'bookme-e1f35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG7pP27px3Fw3VUjWqjgIKA6oDihVXc7w',
    appId: '1:433205296996:ios:39ada4fafd3bc3fd384471',
    messagingSenderId: '433205296996',
    projectId: 'bookme-e1f35',
    storageBucket: 'bookme-e1f35.firebasestorage.app',
    iosBundleId: 'sg.psychologyclinic.bookme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG7pP27px3Fw3VUjWqjgIKA6oDihVXc7w',
    appId: '1:433205296996:ios:0b10a5184aba2e4d384471',
    messagingSenderId: '433205296996',
    projectId: 'bookme-e1f35',
    storageBucket: 'bookme-e1f35.firebasestorage.app',
    iosBundleId: 'com.example.bookme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW0Vk__nXs7ve1-o4M5LQeAEH-cmC8PBE',
    appId: '1:433205296996:web:dedbe466c5772194384471',
    messagingSenderId: '433205296996',
    projectId: 'bookme-e1f35',
    authDomain: 'bookme-e1f35.firebaseapp.com',
    storageBucket: 'bookme-e1f35.firebasestorage.app',
    measurementId: 'G-PS2DLDJYWY',
  );
}
